################################################################################################
# Estimation and Inference in Boundary Discontinuity Designs: Location-Based Methods
# Empirical Application: SPP Data
# Replication output
################################################################################################

rm(list = ls(all = TRUE))

# This script is the source of all replication CSV files used by the
# table and figure scripts. It runs the fuzzy location-based specification for
# the main outcome and the covariate-balance outcome, then writes summary()
# tables with confidence bands, WBATE, and LBATE rows included.

get_script_dir <- function() {
  file_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(file_arg) > 0) {
    return(normalizePath(dirname(sub("^--file=", "", file_arg[1])), winslash = "/"))
  }
  normalizePath(getwd(), winslash = "/")
}

setwd(get_script_dir())

output_dir <- "output"
dir.create(output_dir, showWarnings = FALSE)

set.seed(20260501)
repp <- 2000
repp_env <- Sys.getenv("RD2D_EMP_REPP", unset = "")
if (!identical(repp_env, "")) {
  repp <- suppressWarnings(as.integer(repp_env))
  if (is.na(repp) || repp <= 0) {
    stop("RD2D_EMP_REPP must be a positive integer.", call. = FALSE)
  }
}

# Each row describes one rd2d() fit. The output column identifies which summary
# tables are written from that fit.
outcome_specs <- list(
  list(
    prefix = "main",
    outcome = "Y",
    outputs = c("main", "itt", "fs", "itt.0")
  ),
  list(
    prefix = "covbal",
    outcome = "Z",
    outputs = "itt"
  )
)

bw_specs <- data.frame(
  bwparam = c("main", "itt"),
  suffix = c("bwmain", "bwitt"),
  stringsAsFactors = FALSE
)

################################## Package #####################################

library(rd2d)

rd2d_package_version <- function() {
  desc_path <- system.file("DESCRIPTION", package = "rd2d")
  if (!nzchar(desc_path)) {
    stop("Could not find installed rd2d DESCRIPTION file.", call. = FALSE)
  }
  as.character(read.dcf(desc_path, fields = "Version")[1, 1])
}

check_rd2d_package <- function() {
  # Fail early if R is loading an older installed build rather than the current
  # local API used by this empirical script.
  missing_args <- setdiff(c("params.other", "params.cov", "bwparam"), names(formals(rd2d::rd2d)))
  if (length(missing_args) > 0) {
    stop(
      paste(
        "The installed rd2d package does not match the replication API.",
        "Install or update rd2d from CRAN before running this script.",
        "Missing rd2d() argument(s):",
        paste(missing_args, collapse = ", ")
      ),
      call. = FALSE
    )
  }

  cat(sprintf("Using rd2d version: %s\n", rd2d_package_version()))
}

################################## Setup #######################################

clean_output_dir <- function() {
  # Only remove files generated by this replication-output script.
  old_files <- list.files(output_dir, pattern = "^(rd2d_)?empapp_.*\\.csv$", full.names = TRUE)
  if (length(old_files) > 0) unlink(old_files)
}

write_output_csv <- function(x, file) {
  write.csv(x, file.path(output_dir, file), row.names = FALSE, na = "")
}

################################## Data ########################################

load_spp_data <- function(path = "spp.csv") {
  raw <- read.csv(path)
  expected <- c(
    "running_saber11", "running_sisben", "eligible_spp",
    "beneficiary_spp", "spadies_any", "icfes_educm1"
  )
  missing_cols <- setdiff(expected, names(raw))
  if (length(missing_cols) > 0) {
    stop(sprintf("spp.csv is missing columns: %s", paste(missing_cols, collapse = ", ")), call. = FALSE)
  }

  spp <- raw[, expected]
  names(spp) <- c("x.1", "x.2", "assignment", "fuzzy", "Y", "Z")

  # Assignment should be implied by the two running variables and the boundary.
  expected_assignment <- as.integer(spp$x.1 >= 0 & spp$x.2 >= 0)
  if (!all(spp$assignment == expected_assignment, na.rm = TRUE)) {
    stop("eligible_spp does not match 1{x.1 >= 0 & x.2 >= 0}.", call. = FALSE)
  }

  spp
}

make_eval_grid <- function(neval = 40) {
  # The 40 evaluation points trace the two arms of the SPP eligibility boundary:
  # first Saber 11 = 0, then Sisben = 0.
  half <- ceiling(neval / 2)
  rbind(
    data.frame(
      x.1 = rep(0, half),
      x.2 = 40 - (seq_len(half) - 1) * 40 / half
    ),
    data.frame(
      x.1 = (seq_len(neval - half) - 1) * 56 / half,
      x.2 = rep(0, neval - half)
    )
  )
}

prepare_outcome_data <- function(spp, outcome) {
  # rd2d() takes one outcome at a time. Rename the active outcome to Y_now so
  # the estimation code is shared across main and covariate-balance fits.
  keep <- complete.cases(spp[, c("x.1", "x.2", "assignment", "fuzzy", outcome)])
  dat <- spp[keep, c("x.1", "x.2", "assignment", "fuzzy", outcome), drop = FALSE]
  names(dat)[names(dat) == outcome] <- "Y_now"
  dat
}

################################ Estimation ####################################

run_fuzzy_fit <- function(dat, eval, bwparam) {
  # We request itt.0 as the only one-sided table and request covariance matrices
  # for every table that will use confidence bands or aggregate inference.
  rd2d::rd2d(
    Y = dat$Y_now,
    X = as.matrix(dat[, c("x.1", "x.2")]),
    assignment = dat$assignment,
    b = eval,
    fuzzy = dat$fuzzy,
    bwparam = bwparam,
    params.other = "itt.0",
    params.cov = c("main", "itt", "fs", "itt.0"),
    repp = repp
  )
}

make_summary_table <- function(fit, output) {
  point_table <- fit[[output]]
  if (!is.data.frame(point_table)) {
    stop(sprintf("Output '%s' was not computed.", output), call. = FALSE)
  }

  # summary() appends WBATE/LBATE as rows. capture.output() suppresses console
  # printing because the CSV is the object used downstream.
  invisible(utils::capture.output(
    summary_fit <- summary(
      fit,
      output = output,
      cbands = output,
      WBATE = rep(1, nrow(point_table)),
      LBATE = TRUE
    )
  ))

  summary_table <- summary_fit$tables[[output]]
  data.frame(row = rownames(summary_table), summary_table, check.names = FALSE)
}

output_id <- function(prefix, output, suffix) {
  output_clean <- gsub(".", "", output, fixed = TRUE)
  if (identical(prefix, "main") && identical(output_clean, "main")) {
    return(paste("empapp_main_fuzzy", suffix, sep = "_"))
  }
  parts <- c("empapp", prefix)
  if (!identical(prefix, output_clean)) {
    parts <- c(parts, output_clean)
  }
  paste(c(parts, suffix), collapse = "_")
}

make_percent_table <- function(suffix) {
  # Derived effect-size table. Ratios are computed row by row from the summary
  # outputs, including WBATE/LBATE rows.
  fuzzy <- read.csv(file.path(output_dir, paste0("empapp_main_fuzzy_", suffix, ".csv")), check.names = FALSE)
  itt <- read.csv(file.path(output_dir, paste0("empapp_main_itt_", suffix, ".csv")), check.names = FALSE)
  itt0 <- read.csv(file.path(output_dir, paste0("empapp_main_itt0_", suffix, ".csv")), check.names = FALSE)

  if (!identical(fuzzy$row, itt$row) || !identical(fuzzy$row, itt0$row)) {
    stop("Cannot construct percent table because summary rows do not align.", call. = FALSE)
  }

  denom <- itt0$estimate.p
  percent <- data.frame(
    row = fuzzy$row,
    b1 = fuzzy$b1,
    b2 = fuzzy$b2,
    h01 = fuzzy$h01,
    h02 = fuzzy$h02,
    h11 = fuzzy$h11,
    h12 = fuzzy$h12,
    N.Co = fuzzy$N.Co,
    N.Tr = fuzzy$N.Tr,
    itt.percent = 100 * itt$estimate.p / denom,
    fuzzy.percent = 100 * fuzzy$estimate.p / denom,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
  percent
}

write_summary_tables <- function(fit, prefix, outputs, suffix) {
  vapply(outputs, function(output) {
    id <- output_id(prefix, output, suffix)
    write_output_csv(make_summary_table(fit, output), paste0(id, ".csv"))
    id
  }, character(1))
}

run_outcome_spec <- function(spp, eval, spec, bwparam, suffix) {
  dat <- prepare_outcome_data(spp, spec$outcome)
  fit <- run_fuzzy_fit(dat, eval, bwparam)
  write_summary_tables(fit, spec$prefix, spec$outputs, suffix)
}

run_bandwidth_spec <- function(spp, eval, bwparam, suffix) {
  cat(sprintf("Running empirical application with bwparam='%s'.\n", bwparam))
  generated_ids <- unlist(
    lapply(outcome_specs, function(spec) {
      run_outcome_spec(spp, eval, spec, bwparam, suffix)
    }),
    use.names = FALSE
  )
  percent_id <- paste("empapp_main_percent", suffix, sep = "_")
  write_output_csv(make_percent_table(suffix), paste0(percent_id, ".csv"))
  c(generated_ids, percent_id)
}

################################ Sanity Checks #################################

check_expected_outputs <- function(ids) {
  expected <- c(
    "empapp_data.csv",
    "empapp_eval.csv",
    "empapp_metadata.csv",
    paste0(ids, ".csv")
  )
  missing <- expected[!file.exists(file.path(output_dir, expected))]
  if (length(missing) > 0) {
    stop(sprintf("Missing expected output file(s): %s", paste(missing, collapse = ", ")), call. = FALSE)
  }
  invisible(expected)
}

################################### Run ########################################

check_rd2d_package()
clean_output_dir()

spp <- load_spp_data("spp.csv")
eval <- make_eval_grid()

# Data/eval/metadata are kept for downstream tables, figures, and reproducibility.
write_output_csv(spp, "empapp_data.csv")
write_output_csv(eval, "empapp_eval.csv")
write_output_csv(
  data.frame(
    name = c("rd2d.version", "repp", "bwparams", "generated_at"),
    value = c(
      rd2d_package_version(),
      as.character(repp),
      paste(paste(bw_specs$bwparam, bw_specs$suffix, sep = "="), collapse = "; "),
      as.character(Sys.time())
    ),
    stringsAsFactors = FALSE
  ),
  "empapp_metadata.csv"
)

generated_ids <- unlist(
  lapply(seq_len(nrow(bw_specs)), function(i) {
    run_bandwidth_spec(
      spp = spp,
      eval = eval,
      bwparam = bw_specs$bwparam[i],
      suffix = bw_specs$suffix[i]
    )
  }),
  use.names = FALSE
)
expected <- check_expected_outputs(generated_ids)

cat("Empirical application output data complete.\n")
cat(sprintf("CSV outputs written to: %s\n", output_dir))
cat(sprintf("Generated %d CSV file(s).\n", length(expected)))
